// src/components/Project.vue
<script>
export default {
    data() {
        return {
            projectNameFormatted: this.projectName.toLowerCase().replace(/ /, ""),
        }
    },
    props: {
        projectName: String,
        projectLink: String,
    }
}
</script>

<template>
    <!-- <p v-if="loading">Loading...</p> -->
    <a class="project" :id="projectNameFormatted" :href="projectLink">
        <figure>
            <img :src="`@/assets/images/${projectNameFormatted}.png`" height="200" width="200">
            <figcaption>{{ projectName }}</figcaption>
        </figure>
    </a>
</template>

// islands/Project.tsx
/** @jsx h */
import { h } from "preact";
import { useState } from "preact/hooks";

interface ProjectProps {
    projectName: string,
    projectLink: string,
}
export default function Project(props: ProjectProps) {
    const projectNameFormatted = props.projectName.toLowerCase().replace(/ /, "");
    return (
        <div>
            <a class="project" id={projectNameFormatted} href={props.projectLink}>
                <figure>
                    <img src={`images/${projectNameFormatted}.png`} height="200" width="200" />
                    <figcaption>{props.projectName}</figcaption>
                </figure>
            </a>
        </div >
    );
}
